language: node_js
node_js:
  - "6"
  - "7"
  - "8"
script: "npm run-script test-cover"
# Send coverage data to Coveralls
after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"